### ISSUE TITLE
jest + enzyme rc3 issue

### ISSUE THREAD

**Issue by Kepro** [JedWatson/react-select#1567]
### Thanks for using react-select!

if I want to test latest rc3 version of react-select then I get error test

````
    TypeError: Argument is NaN
      
      at Object.conversions.unrestricted double (node_modules/webidl-conversions/lib/index.js:110:15)
      at HTMLDivElement.set [as scrollTop] (node_modules/jsdom/lib/jsdom/living/generated/Element.js:496:43)
      at Object.componentDidUpdate (node_modules/react-select/lib/Select.js:262:23)
      at measureLifeCyclePerf (node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
      at node_modules/react-dom/lib/ReactCompositeComponent.js:729:11
      at CallbackQueue.notifyAll (node_modules/react-dom/lib/CallbackQueue.js:76:22)
      at ReactReconcileTransaction.close (node_modules/react-dom/lib/ReactReconcileTransaction.js:80:26)
      at ReactReconcileTransaction.closeAll (node_modules/react-dom/lib/Transaction.js:206:25)
      at ReactReconcileTransaction.perform (node_modules/react-dom/lib/Transaction.js:153:16)
      at ReactUpdatesFlushTransaction.perform (node_modules/react-dom/lib/Transaction.js:140:20)
````

rc1 works perfectly are this issue of react select or jest by it self?

my test is:
`````
const select = wrapper.find('Select');

    expect(select).toHaveLength(1);

    expect(select.find('.Select-value-label').text()).toBe('before');

    const input = select.find('input');

    expect(input).toHaveLength(1);

    input.simulate('focus');
    input.simulate('change', { target: { value: 'test' } });
    input.simulate('keyDown', { keyCode: 13 });

    await wait(50); // 50 is in editor

    expect(valueToTest).toBe('test');

````

the problem is change event

same issue if i use 
````
ReactTestUtils.Simulate.change(input.get(0), { target: { value: 'test' } });
````

if I comment out focus also keyDown is donen't matter :'(

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
