### ISSUE TITLE
react-select with webpack dev server and hot reload crashes

### ISSUE THREAD

**Issue by olemartin** [JedWatson/react-select#3558]
I am not able to reproduce this other than locally :-/

I get this error whenever I click on a react-select element:
```
Uncaught Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at invariant (http://localhost:8080/public/app.js:181388:15)
    at scheduleWork (http://localhost:8080/public/app.js:201249:5)
    at Object.enqueueSetState (http://localhost:8080/public/app.js:192502:5)
    at MenuPlacer../node_modules/react/cjs/react.development.js.Component.setState (http://localhost:8080/public/app.js:229658:16)
    at Object.ref (http://localhost:8080/public/app.js:212984:13)
    at ref (http://localhost:8080/public/app.js:172916:31)
    at commitAttachRef (http://localhost:8080/public/app.js:198828:7)
    at commitAllLifeCycles (http://localhost:8080/public/app.js:200074:7)
    at HTMLUnknownElement.callCallback (http://localhost:8080/public/app.js:181482:14)
    at Object.invokeGuardedCallbackDev (http://localhost:8080/public/app.js:181532:16)
```

When building with webpack, this error goes away.

**Comment by olemartin** [comment]
I upgraded to latest version of react-select, but the error is still present. If I am the only one with this error, we have probably done something wrong. Do you guys have any tips for me?

**Comment by bladey** [comment]
Hi @olemartin, wanted to check in and see if you resolved this.

**Comment by olemartin** [comment]
Hi @bladey. No, when running with hot reload the error is still present. I have to build locally in order to get it working, and that makes the development roundtrip a bit long.

**Comment by ebonow** [comment]
@olemartin Would you mind sharing your code implementation for Select? 

I don't know that I have ever run into this before except when I have perhaps inadvertently passed in a function evaluation instead of a reference. For example...

```js 
const [ input, setInput ] = useState();
const onInputChange = setInput(input)
return <Select onInputChange={onInputChange} {...otherProps} />
```
instead of 
```js 
const [ input, setInput ] = useState();
const onInputChange = input => setInput(input)
return <Select onInputChange={onInputChange} {...otherProps} />
```

Maybe not a great example, but check to make sure all of your function references are references ESPECIALLY those that would cause a state change.

This doesn't appear an issue for others, but curious if you were able to get this resolved. Please let me know and if you still aren't sure what's going on, you can share your code implementation, and we can re-open this.
