### ISSUE TITLE
Errors importing from react-dom

### ISSUE THREAD

**Issue by breadadams** [JedWatson/react-select#3728]
We're using `react-select` for a UI component library, bundling it with microbundle. On build we're seeing the following errors:

```bash
Error: 'createPortal' is not exported by node_modules/react-dom/index.js

at /Users/breadadams/dev/project/node_modules/react-select/dist/chunk-5d200a41.browser.esm.js:13:9

11: import { Component } from 'react';
12: import { jsx, keyframes, ClassNames } from '@emotion/core';
13: import { createPortal } from 'react-dom';
             ^
14: import PropTypes from 'prop-types';
15: import _typeof from '@babel/runtime/helpers/esm/typeof';

===

Error: 'findDOMNode' is not exported by node_modules/react-dom/index.js

at /Users/breadadams/dev/project/node_modules/react-select/dist/base/dist/react-select-a34e9d12.browser.esm.js:15:9

13: import memoizeOne from 'memoize-one';
14: import { jsx } from '@emotion/core';
15: import { findDOMNode } from 'react-dom';
             ^
```

I believe it's because `react-dom` exports `ReactDOM`, and then the methods are accessed off that.

**Comment by breadadams** [comment]
We were missing `react-dom` from our peer dependencies 😅🤦‍♂

**Comment by dinfyru** [comment]
react-select 3.0.8
```
[!] Error: 'createPortal' is not exported by node_modules/react-dom/index.js
https://rollupjs.org/guide/en#error-name-is-not-exported-by-module-
node_modules/react-select/dist/chunk-80640036.esm.js (13:9)
11: import { Component } from 'react';
12: import { jsx, keyframes, ClassNames } from '@emotion/core';
13: import { createPortal } from 'react-dom';
             ^
```
