### ISSUE TITLE
React-select 4.2.0 and NextJS ends up in document not defined

### ISSUE THREAD

**Issue by mercteil** [JedWatson/react-select#4476]
After updating from 4.1.0 to 4.2.0 my NextJS app does not start anymore throwing the error below.

It seems to be an issue with the usage of document and ssr. Document usually cannot be used within the server side since undefined. Fallback to 4.1.0 resolves the issue.

```javascript
error - ReferenceError: document is not defined
    at Object.<anonymous> (/node_modules/react-select/dist/index-1793e281.cjs.dev.js:359:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/node_modules/react-select/dist/Select-59696ec1.cjs.dev.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/node_modules/react-select/dist/react-select.cjs.dev.js:5:29)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)

**Comment by mercteil** [comment]
Importing it dynamically is kind of a shaby solution

```javascript
import dynamic from 'next/dynamic';
const Select = dynamic(() => import('react-select'), { ssr: false });
```

However you end up in a way more complicated code especially when you have something like (where everything becomes undefined)
```javascript
const ClearIndicator = (props) => (
  <Select.components.ClearIndicator {...props}>
    <CancelIcon />
  </Select.components.ClearIndicator>
);

**Comment by joakim-roos** [comment]
Same issue here. We had to set it to 4.1.0 for it to work.

**Comment by Rall3n** [comment]
@ebonow Seems like something that was introduced with #4437.

But shouldn´t the build process for non-browser modules handle something like this?

**Comment by Methuselah96** [comment]
The build process for non-browser modules doesn't do any modifications. Previously the build process for browser modules stripped out checks for `typeof window !== 'undefined'` and `typeof document !== 'undefined'`. We should update the code in question to include the check for `document`.

If @ebonow doesn't beat me to it, I can create and release a patch PR within the next few hours.

**Comment by jhonnyizidoro** [comment]
Same issue here. Downgrading to 4.1.0 worked for now.

**Comment by ebonow** [comment]
Greetings and sorry for the errors everyone. I am putting together a code environment to test the PR to patch this and hope to have this released in the next hour.

**Comment by stefcameron** [comment]
I'm seeing this too. SSR Gtasby build is broken as a result of https://github.com/JedWatson/react-select/pull/4437

@ebonow Thanks for looking into fixing it!

**Comment by ebonow** [comment]
@mercteil , @joakim-roos , @jhonnyizidoro , @stefcameron 

We have released a patch for version 4.2.1. Please kindly take a look and verify that this resolves your issues.

**Comment by ebonow** [comment]
It may also be worth mentioning that the new documentation for react-select is being worked on now and will be served from Next.js, so hopefully SSR considerations will be caught much sooner in the process.

**Comment by jhonnyizidoro** [comment]
@ebonow it is working perfectly now! Thanks <3

**Comment by stefcameron** [comment]
@ebonow Thank you for the quick turn around, much appreciated! Our builds are successful once again with 4.2.1. 🎉
