### ISSUE TITLE
Cannot build a package that depends on react-select

### ISSUE THREAD

**Issue by davidgoli** [JedWatson/react-select#4828]
Minimal repro:  https://github.com/davidgoli/react-select-repro

1. Create a package that imports react-select and adds functionality to it
2. Build that package for 3rd part use via webpack or rollup, and configure it to emit types (.d.ts files)

Result:

```
src/index.tsx → dist/index.js...
[!] (plugin rpt2) Error: /Users/davidgolightly/dev/react-select-repro/src/select.tsx(3,14): semantic error TS4023: Exported variable 'SelectTheme' has or is using name 'ThemeSpacing' from external module "/Users/davidgolightly/dev/react-select-repro/node_modules/react-select/dist/declarations/src/types" but cannot be named.
src/select.tsx
Error: /Users/davidgolightly/dev/react-select-repro/src/select.tsx(3,14): semantic error TS4023: Exported variable 'SelectTheme' has or is using name 'ThemeSpacing' from external module "/Users/davidgolightly/dev/react-select-repro/node_modules/react-select/dist/declarations/src/types" but cannot be named.
    at error (/Users/davidgolightly/dev/react-select-repro/node_modules/rollup/dist/shared/rollup.js:158:30)
    at throwPluginError (/Users/davidgolightly/dev/react-select-repro/node_modules/rollup/dist/shared/rollup.js:21741:12)
    at Object.error (/Users/davidgolightly/dev/react-select-repro/node_modules/rollup/dist/shared/rollup.js:22415:20)
    at Object.error (/Users/davidgolightly/dev/react-select-repro/node_modules/rollup/dist/shared/rollup.js:21917:38)
    at RollupContext.error (/Users/davidgolightly/dev/react-select-repro/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:17241:30)
    at /Users/davidgolightly/dev/react-select-repro/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:25064:23
    at arrayEach (/Users/davidgolightly/dev/react-select-repro/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:549:11)
    at Function.forEach (/Users/davidgolightly/dev/react-select-repro/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:9401:14)
    at printDiagnostics (/Users/davidgolightly/dev/react-select-repro/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:25037:12)
    at /Users/davidgolightly/dev/react-select-repro/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:30114:21
```

Expected: build succeeds without error

Possible fix: 

In https://github.com/JedWatson/react-select/blob/23517d1e62f9371d795dd3ccd6746c7f1e4b55ee/packages/react-select/src/types.ts#L45, change the line to `export interface ThemeSpacing {`. This is confirmed to fix the issue.

Using react-select v5.0.0.

**Comment by Methuselah96** [comment]
Thanks for the issue, I've added those exports to https://github.com/JedWatson/react-select/pull/4801.
