### ISSUE TITLE
Warning: Unknown event handler property `onExited`

### ISSUE THREAD

**Issue by A-Vershinin** [JedWatson/react-select#4922]
I'm using Nextjs v.11 and Select version last v.5.2.1
Got issue the same https://github.com/JedWatson/react-select/issues/2607
It still actual, got two warnings

First
```
react-dom.development.js?61bb:67 Warning: Unknown event handler property `onExited`. It will be ignored.
    at input
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-1c22787f.browser.esm.js:55:66)
    at DummyInput (webpack-internal:///./node_modules/react-select/dist/Select-09b3775e.esm.js:576:23)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-1c22787f.browser.esm.js:55:66)
    at ValueContainer (webpack-internal:///./node_modules/react-select/dist/index-c7a4d7ce.esm.js:936:24)
    at TransitionGroup (webpack-internal:///./node_modules/react-transition-group/esm/TransitionGroup.js:54:30)
    at eval (webpack-internal:///./node_modules/react-select/animated/dist/react-select.esm.js:270:18)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-1c22787f.browser.esm.js:55:66)
    at Control (webpack-internal:///./node_modules/react-select/dist/index-c7a4d7ce.esm.js:1200:24)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-1c22787f.browser.esm.js:55:66)
    at SelectContainer (webpack-internal:///./node_modules/react-select/dist/index-c7a4d7ce.esm.js:901:24)
    at Select (webpack-internal:///./node_modules/react-select/dist/Select-09b3775e.esm.js:1177:87)
    at eval (webpack-internal:///./node_modules/react-select/dist/react-select.esm.js:53:92)
    at _c5 (webpack-internal:///./src/components/ui/FormFields/InputSelect/component.tsx:207:25)
    at Controller (webpack-internal:///./node_modules/react-hook-form/dist/index.esm.js:307:37)
    at WrappedFormSelect (webpack-internal:///./src/components/common/WrappedFormSelect/component.tsx:57:20)
    at eval (webpack-internal:///./node_modules/antd/lib/form/FormItem.js:78:23)
```
Second
```
Warning: Received `true` for a non-boolean attribute `in`.

If you want to write it to the DOM, pass a string instead: in="true" or in={value.toString()}.
    at input
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-1c22787f.browser.esm.js:55:66)
    at DummyInput (webpack-internal:///./node_modules/react-select/dist/Select-09b3775e.esm.js:576:23)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-1c22787f.browser.esm.js:55:66)
    at ValueContainer (webpack-internal:///./node_modules/react-select/dist/index-c7a4d7ce.esm.js:936:24)
    at TransitionGroup (webpack-internal:///./node_modules/react-transition-group/esm/TransitionGroup.js:54:30)
    at eval (webpack-internal:///./node_modules/react-select/animated/dist/react-select.esm.js:270:18)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-1c22787f.browser.esm.js:55:66)
    at Control (webpack-internal:///./node_modules/react-select/dist/index-c7a4d7ce.esm.js:1200:24)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-1c22787f.browser.esm.js:55:66)
    at SelectContainer (webpack-internal:///./node_modules/react-select/dist/index-c7a4d7ce.esm.js:901:24)
    at Select (webpack-internal:///./node_modules/react-select/dist/Select-09b3775e.esm.js:1177:87)
    at eval (webpack-internal:///./node_modules/react-select/dist/react-select.esm.js:53:92)
    at _c5 (webpack-internal:///./src/components/ui/FormFields/InputSelect/component.tsx:207:25)
    at Controller (webpack-internal:///./node_modules/react-hook-form/dist/index.esm.js:307:37)
    at WrappedFormSelect (webpack-internal:///./src/components/common/WrappedFormSelect/component.tsx:57:20)
    at eval (webpack-internal:///./node_modules/antd/lib/form/FormItem.js:78:23)

```

**Comment by ebonow** [comment]
@A-Vershinin 

The props `onExited` and `in` are used by CSSTransitionGroup for animated components. 

How are you using defining your types and importing your Select?

**Comment by A-Vershinin** [comment]
I apologize for long delay with answer

This is my custom Select component. It's full components with custom option items and some types for typescript. 
```
import React, { forwardRef, Ref, FC, ReactElement } from "react";
import cx from "classnames";
import { LoadingOutlined } from "@ant-design/icons";
import { NestedSelectedItem } from "models";
import st from "./Styles.module.less";
import { Icon } from "components";

// Select 
import Select, {
  Props,
  SelectInstance as ReactSelectInstance,
  SingleValueProps,
  MultiValueProps,
  OptionProps,
  components as selectComponents,
  StylesConfig,
  DropdownIndicatorProps,
  ControlProps,
} from "react-select";
import makeAnimated from "react-select/animated";


// Wrapper for react-hook-form
const components = { ...selectComponents, ...makeAnimated() };

type ControlPropsType = ControlProps<NestedSelectedItem>;
const Control: FC<ControlPropsType> = ({ children, ...rest }): ReactElement => {
  return <components.Control {...rest}>{children}</components.Control>;
};

// Select custom options

type SelectItemValueProps = SingleValueProps<NestedSelectedItem>;
const SelectItemValue: FC<SelectItemValueProps> = (props): ReactElement => {
  const { data } = props;

  return (
    <components.SingleValue {...props} className={st.selectItem}>
      {data?.icon && <Icon name={data.icon} />} {data?.label}
    </components.SingleValue>
  );
};

type SelectItemMultiValueProps = MultiValueProps<NestedSelectedItem>;
const SelectItemMultiValue: FC<SelectItemMultiValueProps> = (props): ReactElement => {
  const { data } = props;

  return (
    <components.MultiValue {...props}>
      {data?.icon && <Icon name={data.icon} />} {data?.label}
    </components.MultiValue>
  );
};

type SelectItemOptionProps = OptionProps<NestedSelectedItem>;
const SelectItemOption: FC<SelectItemOptionProps> = (props): ReactElement => {
  const { data } = props;

  return (
    <components.Option {...props}>
      {data?.icon && <Icon name={data.icon} />} {data?.label}
    </components.Option>
  );
};
// Select Arrow
type SelectIndicatorProps = DropdownIndicatorProps<NestedSelectedItem> & { loading?: boolean };
const SelectIndicator: FC<SelectIndicatorProps> = (props): ReactElement => {
  const { selectProps, loading } = props;

  return (
    <components.DropdownIndicator {...props}>
      {loading ? (
        <LoadingOutlined />
      ) : selectProps.menuIsOpen ? (
        <Icon name="UpOutlined" />
      ) : (
        <Icon name="DownOutlined" />
      )}
    </components.DropdownIndicator>
  );
};



// Main Select
const colourStyles = (isValid: boolean): StylesConfig<any> => ({
  control: (styles) => {
    return {
    ....
});

export type InputSelectProps = Props<NestedSelectedItem> & {
  hasDisabled?: boolean;
  hasPrefix?: boolean;
  hasSearch?: boolean;
  hasValid?: boolean;
  hasFocused?: boolean;
  prefixNumber?: number;
  hasPrefixControl?: boolean;
  loading?: boolean;
};
type SelectInstance = ReactSelectInstance<NestedSelectedItem>;


export const InputSelect = forwardRef(
  (props: InputSelectProps, ref: Ref<SelectInstance>): ReactElement => {
    const {
      className,
      prefixNumber,
      hasDisabled = false,
      hasPrefix = false,
      hasSearch = false,
      hasValid = true,
      hasFocused = false,
      hasPrefixControl = false,
      loading = false,
      ...rest
    } = props;

    const selectStyle = cx(
      st.select,
      {
        [st.disabled]: hasDisabled,
        [st.prefix]: hasPrefix,
        [st.focused]: hasFocused,
      },
      className,
    );

    const prefixControlStyle = cx(st["prefix-control"], {
      [st.active]: hasFocused,
    });

    return (
      <Select
        {...rest}
        classNamePrefix={st.select}
        className={selectStyle}
        components={{
          ...components,
          Control: ({ children, ...controlProps }) => (
            <Control {...controlProps}>
              {hasPrefixControl && <div className={prefixControlStyle}>{prefixNumber}</div>}
              {children}
            </Control>
          ),
          SingleValue: SelectItemValue,
          MultiValue: SelectItemMultiValue,
          Option: SelectItemOption,
          DropdownIndicator: (indicatorProps) => (
            <SelectIndicator loading={loading} {...indicatorProps} />
          ),
        }}
        isDisabled={hasDisabled || loading}
        isSearchable={hasSearch}
        ref={ref}
        styles={colourStyles(hasValid)}
        instanceId={rest.name}
      />
    );
  },
);

```

**Comment by Rall3n** [comment]
`DummyInput` seems to get those transition props despite not being an animated component. We should by default seperate those props from the `props` object for the default `<input>` element.

Until then the only workarounds include either not using the animated components, or not setting `isSearchable = false`, as the `DummyInput` component is an internal component that cannot be easily overwritten by the developing user.

**Comment by A-Vershinin** [comment]
Thanks for help. I'll try to do refactoring
