### ISSUE TITLE
Cannot use 'in' operator to search for 'options' at Select-126cf1dd.esm.js:1033:1

### ISSUE THREAD

**Issue by arnaudambro** [JedWatson/react-select#5032]
Hello

I upgraded to v5 just now and I have this bug coming

```
Select-126cf1dd.esm.js:1033 Uncaught TypeError: Cannot use 'in' operator to search for 'options' in 00000000-5f63-1c20-3924-517713f97cc6
    at Select-126cf1dd.esm.js:1033:1
    at Array.map (<anonymous>)
    at buildCategorizedOptions (Select-126cf1dd.esm.js:1032:1)
    at Select._this.buildCategorizedOptions (Select-126cf1dd.esm.js:1371:1)
    at Select._this.buildFocusableOptions (Select-126cf1dd.esm.js:1379:1)
    at Select.openMenu (Select-126cf1dd.esm.js:1918:1)
    at Select._this.onInputFocus (Select-126cf1dd.esm.js:1589:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4070:1)
    at executeDispatch (react-dom.development.js:8243:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:8275:1)
    at processDispatchQueue (react-dom.development.js:8288:1)
    at dispatchEventsForPlugins (react-dom.development.js:8299:1)
    at react-dom.development.js:8508:1
    at batchedEventUpdates (react-dom.development.js:3739:1)
    at dispatchEventForPluginEventSystem (react-dom.development.js:8507:1)
    at attemptToDispatchEvent (react-dom.development.js:6005:1)
    at dispatchEvent (react-dom.development.js:5924:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at discreteUpdates$1 (react-dom.development.js:22413:1)
    at discreteUpdates (react-dom.development.js:3756:1)
    at dispatchDiscreteEvent (react-dom.development.js:5889:1)
    at Select.focusInput (Select-126cf1dd.esm.js:1901:1)
    at Select._this.onControlMouseDown (Select-126cf1dd.esm.js:1417:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4070:1)
    at executeDispatch (react-dom.development.js:8243:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:8275:1)
    at processDispatchQueue (react-dom.development.js:8288:1)
    at dispatchEventsForPlugins (react-dom.development.js:8299:1)
    at react-dom.development.js:8508:1
    at batchedEventUpdates$1 (react-dom.development.js:22396:1)
    at batchedEventUpdates (react-dom.development.js:3745:1)
    at dispatchEventForPluginEventSystem (react-dom.development.js:8507:1)
    at attemptToDispatchEvent (react-dom.development.js:6005:1)
    at dispatchEvent (react-dom.development.js:5924:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at discreteUpdates$1 (react-dom.development.js:22413:1)
    at discreteUpdates (react-dom.development.js:3756:1)
    at dispatchDiscreteEvent (react-dom.development.js:5889:1)
```

My code is the following
```JS
      <Select
        options={teams.map(({ _id }) => _id)}
        value={[teamId]}
        onChange={(id) => onChange(teams.find((team) => team._id === id))}
        getOptionValue={(id) => id}
        getOptionLabel={(id) => teams.find((team) => team._id === id)?.name}
        isClearable={false}
      />
```

**Comment by Rall3n** [comment]
Hello @arnaudambro,

`react-select` does not actively support options that are just simple strings.

I recommend you map your "teams" to an object of the shape `{ id, name }` and change the props `getOptionValue` and `getOptionLabel` accordingly.

**Comment by jamespohalloran** [comment]
This stumped me for a while. The docs in the readme don't mention the new format, so very tough to debug

**Comment by zackarydev** [comment]
Can we fix this? Seems trivial...

**Comment by simon-abbott** [comment]
Simple string options are very common for simple selects. There should either be official support for them, or their lack of support should be clearly documented (currently neither the website nor the doc comments mention this) _and_ it should be reflected in the types (passing an array of strings causes no TypeScript error).
