### ISSUE TITLE
window undefined error in server-side rendering

### ISSUE THREAD

**Issue by Eneris** [JedWatson/react-select#608]
There is an issue with sub-module "react-input-autosize" when page is pre-rendered server-side.

```
error given was: ReferenceError: window is not defined
    at \node_modules\react-select\node_modules\react-input-autosize\lib\AutosizeInput.js:10:9
    at Object.<anonymous> (\node_modules\react-select\node_modules\react-input-autosize\lib\AutosizeInput.js:13:3)
    at Module._compile (module.js:460:26)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (\node_modules\babel-core\lib\api\register\node.js:214:7)
    at Module.load (module.js:355:32)
    at Module._load (module.js:310:12)
    at Function.module._load (\node_modules\piping\lib\launcher.js:32:16)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (\node_modules\react-select\lib\Select.js:13:13)
    at Module._compile (module.js:460:26)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (\node_modules\babel-core\lib\api\register\node.js:214:7)
    at Module.load (module.js:355:32)
    at Module._load (module.js:310:12)
```

**Comment by atroche** [comment]
Hi @Eneris, did you end up resolving this? I was hoping to render the component server-side.

**Comment by ryanbooals** [comment]
@atroche Did you end up finding a solution?

**Comment by Eneris** [comment]
No. I just went without server-side rendering this time

**Comment by jsperezg** [comment]
any news? this was supposed to be SSR compatible, however it's not
