### ISSUE TITLE
Build Failing (`gulp dev`)

### ISSUE THREAD

**Issue by seanhess** [JedWatson/react-select#68]
I was all fired up to hack and send you a PR for another issue I found, but I can't get my fork to build. I ran `npm install` and then I get this error on `gulp dev`:

```
/Users/seanhess/sources/react-select/node_modules/gulp-less/index.js:68
    }).done(undefined, cb);
       ^
TypeError: undefined is not a function
    at DestroyableTransform._transform (/Users/seanhess/sources/react-select/node_modules/gulp-less/index.js:68:8)
    at DestroyableTransform.Transform._read (/Users/seanhess/sources/react-select/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/seanhess/sources/react-select/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/seanhess/sources/react-select/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/seanhess/sources/react-select/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/seanhess/sources/react-select/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/Users/seanhess/sources/react-select/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/seanhess/sources/react-select/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/seanhess/sources/react-select/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:104:17)
```

**Comment by JedWatson** [comment]
That's really odd, it works for me. There have been a few updates to various packages, perhaps pull latest, remove your `node_modules` directory and `npm install` again?

**Comment by seanhess** [comment]
I deleted everything, cloned the repo and it works now.  Sorry about that, thanks!
